import type { Tool, NewsArticle } from '@/types'

export const SEED_TOOLS: Tool[] = [
  {
    id: '1',
    name: 'ChatGPT',
    slug: 'chatgpt',
    description:
      'The world\'s most widely used AI assistant for writing, coding, analysis, and conversation. Natively supports Hindi, Tamil, Bahasa Indonesia, Tagalog, and 50+ other languages — making it one of the most accessible AI tools across India and Southeast Asia.',
    url: 'https://chat.openai.com',
    category: 'Writing',
    price_type: 'freemium',
    price_label: 'Free / $20 mo',
    tags: ['chatbot', 'writing', 'multilingual', 'openai', 'gpt-4'],
    region_relevance: ['India', 'Southeast Asia'],
    verified: true,
    created_at: '2024-01-15T00:00:00Z',
  },
  {
    id: '2',
    name: 'GitHub Copilot',
    slug: 'github-copilot',
    description:
      'AI pair programmer trained on billions of lines of code. Suggests entire functions, fixes bugs, and writes tests directly in your IDE. Heavily adopted by Indian engineering teams and SEA tech startups building fast.',
    url: 'https://github.com/features/copilot',
    category: 'Code',
    price_type: 'paid',
    price_label: '$10 / mo',
    tags: ['coding', 'autocomplete', 'github', 'vscode', 'developer-tools'],
    region_relevance: ['India', 'Southeast Asia'],
    verified: true,
    created_at: '2024-01-16T00:00:00Z',
  },
  {
    id: '3',
    name: 'Midjourney',
    slug: 'midjourney',
    description:
      'The gold standard in AI image generation. Create photorealistic or artistic visuals from text prompts via Discord. Used by designers, marketers, and creators across the region for campaigns, branding, and content.',
    url: 'https://midjourney.com',
    category: 'Design',
    price_type: 'paid',
    price_label: 'From $10 / mo',
    tags: ['image-generation', 'art', 'design', 'discord', 'creative'],
    region_relevance: ['India', 'Southeast Asia'],
    verified: true,
    created_at: '2024-01-17T00:00:00Z',
  },
  {
    id: '4',
    name: 'Runway ML',
    slug: 'runway-ml',
    description:
      'Next-generation AI video creation. Generate, edit, and transform video from text or images using Gen-2 and Gen-3 models. A go-to tool for video creators, ad agencies, and filmmakers across Asia.',
    url: 'https://runwayml.com',
    category: 'Video',
    price_type: 'freemium',
    price_label: 'Free / from $15 mo',
    tags: ['video-generation', 'gen-2', 'creative', 'editing', 'animation'],
    region_relevance: ['India', 'Southeast Asia'],
    verified: true,
    created_at: '2024-01-18T00:00:00Z',
  },
  {
    id: '5',
    name: 'Perplexity AI',
    slug: 'perplexity-ai',
    description:
      'An AI-powered answer engine that searches the web and provides cited, up-to-date responses. Ideal for researchers, students, and professionals who need accurate information fast — popular in Indian academic circles.',
    url: 'https://perplexity.ai',
    category: 'Research',
    price_type: 'freemium',
    price_label: 'Free / $20 mo',
    tags: ['search', 'research', 'citations', 'real-time', 'web-search'],
    region_relevance: ['India', 'Southeast Asia'],
    verified: true,
    created_at: '2024-01-19T00:00:00Z',
  },
  {
    id: '6',
    name: 'Notion AI',
    slug: 'notion-ai',
    description:
      'AI writing assistant built natively into Notion. Draft documents, summarise meeting notes, brainstorm ideas, and translate content — all within your existing workspace. Used widely by Indian and SEA startups.',
    url: 'https://notion.so/product/ai',
    category: 'Writing',
    price_type: 'freemium',
    price_label: '$10 / mo add-on',
    tags: ['writing', 'productivity', 'notes', 'summarisation', 'workspace'],
    region_relevance: ['India', 'Southeast Asia'],
    verified: false,
    created_at: '2024-01-20T00:00:00Z',
  },
  {
    id: '7',
    name: 'Replit',
    slug: 'replit',
    description:
      'AI-powered cloud IDE with a built-in AI model (Ghostwriter) that helps you write, debug, and deploy code from any browser. Hugely popular in India for learning to code and building side projects without local setup.',
    url: 'https://replit.com',
    category: 'Code',
    price_type: 'freemium',
    price_label: 'Free / from $7 mo',
    tags: ['ide', 'cloud', 'coding', 'deployment', 'education'],
    region_relevance: ['India', 'Southeast Asia'],
    verified: false,
    created_at: '2024-01-21T00:00:00Z',
  },
  {
    id: '8',
    name: 'Canva AI',
    slug: 'canva-ai',
    description:
      'Magic Studio brings AI-powered design to Canva — generate images from text, remove backgrounds instantly, auto-resize for every platform, and translate designs. Canva is the most-used design tool across India and SEA.',
    url: 'https://canva.com/ai-image-generator',
    category: 'Design',
    price_type: 'freemium',
    price_label: 'Free / from $15 mo',
    tags: ['design', 'image-generation', 'templates', 'magic-studio', 'social-media'],
    region_relevance: ['India', 'Southeast Asia'],
    verified: true,
    created_at: '2024-01-22T00:00:00Z',
  },
  {
    id: '9',
    name: 'Synthesia',
    slug: 'synthesia',
    description:
      'Create professional AI videos featuring realistic digital avatars — no camera, no studio, no actors. Widely used by enterprise L&D teams and marketing departments across India for training and product explainer videos.',
    url: 'https://synthesia.io',
    category: 'Video',
    price_type: 'paid',
    price_label: 'From $22 / mo',
    tags: ['avatar', 'video-production', 'training', 'enterprise', 'text-to-video'],
    region_relevance: ['India'],
    verified: false,
    created_at: '2024-01-23T00:00:00Z',
  },
  {
    id: '10',
    name: 'Elicit',
    slug: 'elicit',
    description:
      'AI research assistant that finds, summarises, and extracts data from academic papers. Designed for researchers and analysts, Elicit searches millions of papers to answer research questions with citations.',
    url: 'https://elicit.com',
    category: 'Research',
    price_type: 'freemium',
    price_label: 'Free / $10 mo',
    tags: ['research', 'papers', 'academic', 'literature-review', 'citations'],
    region_relevance: ['India', 'Southeast Asia'],
    verified: false,
    created_at: '2024-01-24T00:00:00Z',
  },
]

export const SEED_NEWS: NewsArticle[] = [
  {
    id: '1',
    title: "India's AI Startup Ecosystem Surpasses $2 Billion in Funding in 2024",
    excerpt:
      'Indian AI startups raised over $2B last year as global investors double down on the country\'s engineering talent and growing enterprise AI demand. Key sectors include healthtech, fintech, and edtech AI applications.',
    url: '#',
    source: 'TechCrunch India',
    category: 'Funding',
    region: 'India',
    published_at: '2024-12-10T09:00:00Z',
    created_at: '2024-12-10T09:00:00Z',
  },
  {
    id: '2',
    title: 'Singapore Unveils National AI Strategy 2.0 with $1 Billion Investment',
    excerpt:
      'The Singapore government announced NAS 2.0, a $1B commitment to accelerate AI adoption across public services, manufacturing, and finance. The plan focuses on developing AI talent and regulatory frameworks for Southeast Asia.',
    url: '#',
    source: 'The Straits Times',
    category: 'Policy',
    region: 'Singapore',
    published_at: '2024-12-05T06:00:00Z',
    created_at: '2024-12-05T06:00:00Z',
  },
  {
    id: '3',
    title: 'Generative AI Adoption Among Southeast Asian SMEs Triples in 2024',
    excerpt:
      'A new Tech in Asia report reveals SME adoption of generative AI tools has tripled year-on-year across Vietnam, Thailand, and the Philippines. Customer service chatbots and content creation tools lead the surge.',
    url: '#',
    source: 'Tech in Asia',
    category: 'Business',
    region: 'Southeast Asia',
    published_at: '2024-12-02T08:00:00Z',
    created_at: '2024-12-02T08:00:00Z',
  },
  {
    id: '4',
    title: "IIT Madras Launches India's First Dedicated AI-Only Research Campus",
    excerpt:
      'IIT Madras inaugurated a 10-acre AI research campus focused on foundation models, AI safety, and regional language AI. The institute plans to train 5,000 AI researchers over five years with industry partnerships.',
    url: '#',
    source: 'The Hindu',
    category: 'Education',
    region: 'India',
    published_at: '2024-11-28T07:30:00Z',
    created_at: '2024-11-28T07:30:00Z',
  },
  {
    id: '5',
    title: "Indonesia's GoTo and Grab Race to Embed AI Across Their Super Apps",
    excerpt:
      'Southeast Asia\'s two biggest super apps are in an AI arms race — integrating LLM-powered features into ride-hailing, food delivery, and financial services. Both companies are hiring aggressively from local universities.',
    url: '#',
    source: 'Rest of World',
    category: 'Business',
    region: 'Indonesia',
    published_at: '2024-11-20T10:00:00Z',
    created_at: '2024-11-20T10:00:00Z',
  },
]
